# Site Settings
title: Tushar Sappal's Resume
url: 'http://tusharsappal.github.io/'
baseurl: '/tusharsappal.github.io' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Tushar Sappal
tagline:  Senior Site Reliability Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Software professional with a demonstrated history of working in the computer software industry , having experience in cloud technologies . 
Skilled in Python, Agile Methodologies, Devops and SRE practices.
Strong engineering professional with a Master’s Degree focused in Software Systems from BITS, Pilani.'

#sidebar links
email: sappal.tushar@gmail.com
phone: +91-8510077660
website: tusharsappal.github.io #do not add http://
linkedin: tusharsappal
github: tusharsappal
twitter: '@tusharsappal'
#Update all the sections by editing the files inside _data folder.

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
